<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" class="no-js">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Chapter 28 Power analysis | Core Statistics in R</title>
<meta name="author" content="Matt Castle and Martin van Rongen">
<meta name="description" content="28.1 Objectives  Questions What is power analysis? How can I use power analysis to design better experiments? Objectives Be able to perform power analysis in R Understand the importance of effect...">
<meta name="generator" content="bookdown 0.26 with bs4_book()">
<meta property="og:title" content="Chapter 28 Power analysis | Core Statistics in R">
<meta property="og:type" content="book">
<meta property="og:description" content="28.1 Objectives  Questions What is power analysis? How can I use power analysis to design better experiments? Objectives Be able to perform power analysis in R Understand the importance of effect...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 28 Power analysis | Core Statistics in R">
<meta name="twitter:description" content="28.1 Objectives  Questions What is power analysis? How can I use power analysis to design better experiments? Objectives Be able to perform power analysis in R Understand the importance of effect...">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references --><link rel="shortcut icon" href="favicon.ico">
<link rel="apple-touch-icon" href="apple-touch-icon.png">
<!-- CSS : implied media="all" --><link rel="stylesheet" href="stylesheets/full-stylesheet.css">
<link rel="stylesheet" href="stylesheets/styleguide.css">
<link rel="stylesheet" href="stylesheets/style.css">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><script type="text/javascript" src="//use.typekit.com/hyb5bko.js"></script><script type="text/javascript">try{Typekit.load();}catch(e){}</script><script type="text/javascript">  document.documentElement.className += " js";</script>
</head>
<body class="campl-theme-2" data-spy="scroll" data-target="#toc">

<!--[if lt IE 7]>
<div class="lt-ie9 lt-ie8 lt-ie7">
<![endif]-->
<!--[if IE 7]>
<div class="lt-ie9 lt-ie8">
<![endif]-->
<!--[if IE 8]>
<div class="lt-ie9">
<![endif]-->

	<a href="#primary-nav" class="campl-skipTo">skip to primary navigation</a>
	<a href="#content" class="campl-skipTo">skip to content</a>
	<div class="campl-row campl-global-header">
		<div class="campl-wrap clearfix">
			<div class="campl-header-container campl-column8" id="global-header-controls">
				<a href="http://www.cam.ac.uk" class="campl-main-logo">
					<img alt="University of Cambridge" src="images/interface/main-logo-small.png" height="38px;"></a>

				<ul class="campl-unstyled-list campl-horizontal-navigation campl-global-navigation clearfix">
<li>
						<a href="#study-with-us">Study at Cambridge</a>
					</li>
					<li>
						<a href="#about-the-university">About the University</a>
					</li>
					<li>
						<a href="http://www.cam.ac.uk/research" class="campl-no-drawer">Research at Cambridge</a>
					</li>
				</ul>
</div>

			<div class="campl-column2">
				<div class="campl-quicklinks">
				</div>
			</div>

			<div class="campl-column2">

				<div class="campl-site-search" id="site-search-btn">

					<label for="header-search" class="hidden">Search site</label>
					<div class="campl-search-input">
						<form action="http://search.cam.ac.uk/web" method="get">
						<input id="header-search" type="text" name="query" value="" placeholder="Search"><input type="image" class="campl-search-submit " src="images/interface/btn-search-header.png">
</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="campl-row campl-global-header campl-search-drawer">
		<div class="campl-wrap clearfix">
			<form class="campl-site-search-form" id="site-search-container" action="">
				<div class="campl-search-form-wrapper clearfix">
					<input type="text" class="text" placeholder="Search"><input type="image" class="campl-search-submit" src="images/interface/btn-search.png">
</div>
			</form>
		</div>
	</div>

	<div class="campl-row campl-global-navigation-drawer">

		<div class="campl-wrap clearfix">
			<div class="campl-column12 campl-home-link-container">
				<a href="">Home</a>
			</div>
		</div>
		<div class="campl-wrap clearfix">
			<div class="campl-column12 campl-global-navigation-mobile-list campl-global-navigation-list">
				<div class="campl-global-navigation-outer clearfix" id="study-with-us">
					<ul class="campl-unstyled-list campl-global-navigation-header-container ">
<li><a href="http://www.cam.ac.uk/study-at-cambridge">Study at Cambridge</a></li>
					</ul>
<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list campl-global-navigation-secondary-with-children">
<li>
								<a href="http://www.study.cam.ac.uk/undergraduate/">Undergraduate</a>
								<ul class="campl-global-navigation-tertiary campl-unstyled-list">
<li>
										<a href="http://www.undergraduate.study.cam.ac.uk/courses">Courses</a>
									</li>
									<li>
										<a href="http://www.undergraduate.study.cam.ac.uk/applying">Applying</a>
									</li>
									<li>
										<a href="http://www.undergraduate.study.cam.ac.uk/events">Events and open days</a>
									</li>
								  <li>
										<a href="http://www.undergraduate.study.cam.ac.uk/finance">Fees and finance</a>
									</li>
								  <li>
										<a href="http://www.becambridge.com/">Student blogs and videos</a>
									</li>
								</ul>
</li>
						</ul>
</div>
					<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list campl-global-navigation-secondary-with-children">
<li>
								<a href="http://www.graduate.study.cam.ac.uk/">Graduate</a>
								<ul class="campl-global-navigation-tertiary campl-unstyled-list">
<li>
										<a href="http://www.graduate.study.cam.ac.uk/why-cambridge/welcome-vice-chancellor">Why Cambridge</a>
									</li>
									<li>
										<a href="http://www.graduate.study.cam.ac.uk/courses%0A">Course directory</a>
									</li>
									<li>
									<a href="http://www.graduate.study.cam.ac.uk/how-do-i-apply">How to apply</a>
</li>
									<li><a href="http://www.cambridgestudents.cam.ac.uk/fees-and-funding">Fees and funding</a></li>
									<li><a href="http://www.graduate.study.cam.ac.uk/faqs/applicant">Frequently asked questions</a></li>
								</ul>
</li>
						</ul>
</div>
					<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list last">
<li>
								<a href="http://www.internationalstudents.cam.ac.uk">International students</a>
							</li>
							<li>
								<a href="http://www.ice.cam.ac.uk">Continuing education</a>
							</li>
							<li>
								<a href="http://www.epe.admin.cam.ac.uk/">Executive and professional education</a>
							</li>
							<li>
								<a href="http://www.educ.cam.ac.uk">Courses in education</a>
							</li>
						</ul>
</div>
				</div>

				<div class="campl-global-navigation-outer clearfix" id="about-the-university">
					<ul class="campl-global-navigation-header-container campl-unstyled-list">
<li><a href="http://www.cam.ac.uk/about-the-university">About the University</a></li>
					</ul>
<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list">
<li>
								<a href="http://www.cam.ac.uk/about-the-university/how-the-university-and-colleges-work">How the University and Colleges work</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-the-university/history">History</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-the-university/visiting-the-university">Visiting the University</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-the-university/term-dates-and-calendars">Term dates and calendars</a>
							</li>
							<li class="last">
								<a href="http://map.cam.ac.uk">Map</a>
							</li>
						</ul>
</div>
					<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list">
<li>
								<a href="http://www.communications.cam.ac.uk/">For media</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/video-and-audio">Video and audio</a>
							</li>
							<li>
								<a href="http://webservices.admin.cam.ac.uk/fae/">Find an expert</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-the-university/publications">Publications</a>
							</li>
							<li class="last">
								<a href="http://www.cam.ac.uk/global-cambridge">Global Cambridge</a>
							</li>
						</ul>
</div>
					<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list">
<li>
								<a href="http://www.cam.ac.uk/news">News</a>
							</li>
							<li>
								<a href="http://www.admin.cam.ac.uk/whatson/">Events</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/public-engagement">Public engagement</a>
							</li>
							<li>
								<a href="http://www.jobs.cam.ac.uk">Jobs</a>
							</li>
							<li class="last">
								<a href="https://www.philanthropy.cam.ac.uk/">Give to Cambridge</a>
							</li>
						</ul>
</div>
				</div>

				<div class="campl-global-navigation-outer clearfix" id="our-research">
					<ul class="campl-global-navigation-header-container campl-unstyled-list">
<li><a href="">Research at Cambridge</a></li>
					</ul>
</div>
			</div>

			<ul class="campl-unstyled-list campl-quicklinks-list campl-global-navigation-container ">
<li>
					<a href="http://www.cam.ac.uk/for-staff">For staff</a>
				</li>
				<li>
					<a href="http://www.cam.ac.uk/current-students">For current students</a>
				</li>
				<li>
					<a href="http://www.alumni.cam.ac.uk">For alumni</a>
				</li>
				<li>
					<a href="http://www.cam.ac.uk/for-business">For business</a>
				</li>
				<li>
					<a href="http://www.cam.ac.uk/colleges-and-departments">Colleges &amp; departments</a>
				</li>
				<li>
					<a href="http://www.lib.cam.ac.uk/libraries/">Libraries &amp; facilities</a>
				</li>
				<li>
					<a href="http://www.cam.ac.uk/museums-and-collections">Museums &amp; collections</a>
				</li>
				<li class="last">
					<a href="http://www.cam.ac.uk/email-and-phone-search">Email &amp; phone search</a>
				</li>
			</ul>
</div>
	</div>
    <!-- .campl-global-header ends -->

	<div class="campl-row campl-page-header campl-sub-section-page">
		<div class="campl-wrap clearfix">
			<div class="campl-column12">
				<div class="campl-content-container">
					<div class="campl-breadcrumb" id="breadcrumb">
						<ul class="campl-unstyled-list campl-horizontal-navigation clearfix">
<li class="first-child">
								<a href="https://bioinfotraining.bio.cam.ac.uk/" class="campl-home ir">Home</a>
							</li>
							<li>
								<a href="">Courses</a>
							</li>
							<li>
								<a href="">Training Materials</a>
							</li>
							<li>
								<a href="index.html">Core Statistics in R
							</a>
</li>
						</ul>
</div>
					<!--<p class="campl-page-title">Bioinformatics Training Materials</p>-->

					<p class="campl-mobile-parent"><a href=""><span class="campl-back-btn campl-menu-indicator"></span>Studying at Cambridge</a></p>
				</div>
			</div>
		</div>
	</div>

	<div class="campl-row campl-page-header">
		<div class="campl-wrap clearfix campl-local-navigation" id="local-nav">
			<div class="campl-local-navigation-container">
				<ul class="campl-unstyled-list">
<li><a href="https://training.cam.ac.uk/bioinformatics/search">Course schedule</a></li>
					<li>
<a href="#" class="campl-selected">Additional information</a>
						<ul class="campl-unstyled-list local-dropdown-menu">
<li><a href="#">Additional resources</a></li>
							<li><a href="https://bioinfotraining.bio.cam.ac.uk/about/findus">Where to find us?</a></li>
							<li><a href="#">Frequently asked questions</a></li>
						</ul>
</li>
					<li><a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate">Further training</a></li>
				</ul>
</div>
		</div>



		<div class="campl-wrap clearfix campl-page-sub-title campl-recessed-sub-title">
			<div class="campl-column12">
				<div class="campl-content-container">
					<p class="campl-sub-title">Core Statistics in R</p>
				</div>
			</div>
		</div>
	</div>


		<div class="campl-row campl-content campl-recessed-content">
			<div class="campl-wrap clearfix">
				<div class="campl-column9  campl-main-content" id="content">
					<div class="campl-content-container">
						<div>
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <br><button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Overview</a></li>
<li class="book-part">CoreStats 1: Simple hypothesis testing</li>
<li><a class="" href="cs1-intro.html"><span class="header-section-number">2</span> Introduction</a></li>
<li class="book-part">CoreStats 1 (Practicals)</li>
<li><a class="" href="introduction.html"><span class="header-section-number">3</span> Introduction</a></li>
<li><a class="" href="cs1-one-sample-t-test.html"><span class="header-section-number">4</span> One-sample t-test</a></li>
<li><a class="" href="cs1-onesample-wilcoxon-signed-rank.html"><span class="header-section-number">5</span> Wilcoxon signed-rank test</a></li>
<li><a class="" href="cs1-students-t-test.html"><span class="header-section-number">6</span> Student’s t-test</a></li>
<li><a class="" href="cs1-mannwhitney-u-test.html"><span class="header-section-number">7</span> Mann-Whitney U test</a></li>
<li><a class="" href="cs1-paired-two-sample-t-test.html"><span class="header-section-number">8</span> Paired two-sample t-test</a></li>
<li><a class="" href="cs1-twosample-wilcoxon-signed-rank.html"><span class="header-section-number">9</span> Wilcoxon signed-rank test</a></li>
<li class="book-part">CoreStats 2: Categorical predictors</li>
<li><a class="" href="cs2-intro.html"><span class="header-section-number">10</span> Introduction</a></li>
<li class="book-part">CoreStats 2 (Practicals)</li>
<li><a class="" href="introduction-1.html"><span class="header-section-number">11</span> Introduction</a></li>
<li><a class="" href="cs2-anova.html"><span class="header-section-number">12</span> ANOVA</a></li>
<li><a class="" href="kruskal-wallis-test.html"><span class="header-section-number">13</span> Kruskal-Wallis test</a></li>
<li class="book-part">CoreStats 3: Continuous predictors</li>
<li><a class="" href="cs3-intro.html"><span class="header-section-number">14</span> Introduction</a></li>
<li class="book-part">CoreStats 3 (Practicals)</li>
<li><a class="" href="introduction-2.html"><span class="header-section-number">15</span> Introduction</a></li>
<li><a class="" href="correlation-coefficients.html"><span class="header-section-number">16</span> Correlation coefficients</a></li>
<li><a class="" href="linear-regression.html"><span class="header-section-number">17</span> Linear regression</a></li>
<li class="book-part">CoreStats 4: Two predictor variables</li>
<li><a class="" href="cs4-intro.html"><span class="header-section-number">18</span> Introduction</a></li>
<li class="book-part">CoreStats 4 (Practicals)</li>
<li><a class="" href="introduction-3.html"><span class="header-section-number">19</span> Introduction</a></li>
<li><a class="" href="two-way-anova.html"><span class="header-section-number">20</span> Two-way ANOVA</a></li>
<li><a class="" href="linear-regression-with-grouped-data.html"><span class="header-section-number">21</span> Linear regression with grouped data</a></li>
<li class="book-part">CoreStats 5: Multiple predictor variables</li>
<li><a class="" href="cs5-intro.html"><span class="header-section-number">22</span> Introduction</a></li>
<li class="book-part">CoreStats 5 (Practicals)</li>
<li><a class="" href="introduction-4.html"><span class="header-section-number">23</span> Introduction</a></li>
<li><a class="" href="linear-models.html"><span class="header-section-number">24</span> Linear models</a></li>
<li><a class="" href="model-comparisons.html"><span class="header-section-number">25</span> Model comparisons</a></li>
<li class="book-part">CoreStats 6: Power analysis</li>
<li><a class="" href="cs6-intro.html"><span class="header-section-number">26</span> Introduction</a></li>
<li class="book-part">CoreStats 6 (Practicals)</li>
<li><a class="" href="introduction-5.html"><span class="header-section-number">27</span> Introduction</a></li>
<li><a class="active" href="power-analysis.html"><span class="header-section-number">28</span> Power analysis</a></li>
<li><a class="" href="statistical-reporting.html"><span class="header-section-number">29</span> Statistical reporting</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="power-analysis" class="section level1" number="28">
<h1>
<span class="header-section-number">28</span> Power analysis<a class="anchor" aria-label="anchor" href="#power-analysis"><i class="fas fa-link"></i></a>
</h1>
<div id="objectives-14" class="section level2" number="28.1">
<h2>
<span class="header-section-number">28.1</span> Objectives<a class="anchor" aria-label="anchor" href="#objectives-14"><i class="fas fa-link"></i></a>
</h2>
<div class="objectives">
<p><strong>Questions</strong></p>
<ul>
<li>What is power analysis?</li>
<li>How can I use power analysis to design better experiments?</li>
</ul>
<p><strong>Objectives</strong></p>
<ul>
<li>Be able to perform power analysis in R</li>
<li>Understand the importance of effect size</li>
<li>Use power, significance level and effect size to optimise your experimental design</li>
</ul>
</div>
</div>
<div id="background-6" class="section level2" number="28.2">
<h2>
<span class="header-section-number">28.2</span> Background<a class="anchor" aria-label="anchor" href="#background-6"><i class="fas fa-link"></i></a>
</h2>
<p>All hypothesis tests can be wrong in two ways:</p>
<ul>
<li>we can appear to have found a significant result when there really isn’t anything there: a false positive (or Type I error), or</li>
<li>we can fail to spot a significant result when there really is something interesting going on: a false negative (or Type II error).</li>
</ul>
<p>The probability of getting a false positive in our analysis is precisely the significance level we use in our analysis. So, in order to reduce the likelihood of getting a false positive we simply reduce the significance level of our test (from 0.05 down to 0.01 say). Easy as that.</p>
<p>Unfortunately, this has unintended consequences (doesn’t everything?). It turns out that reducing the significance level means that we increase the chance of getting false negatives. This should make sense; if we’re increasing the barrier to entry in terms of acceptance then we’ll also accidentally miss out on some of the good stuff.</p>
<p><strong>Power</strong> is the capacity of a test to detect significant different results. It is affected by three things:</p>
<ol style="list-style-type: decimal">
<li>the effect size: i.e. how big of a difference do you want to be able to detect, or alternatively what do you consider a meaningful effect/difference to be?</li>
<li>sample size</li>
<li>the significance level</li>
</ol>
<p>In an ideal world we would want to be carrying out highly powerful tests using low significance levels, to both reduce our chance of getting a false positive and maximise our chances of finding a true effect.</p>
<p><strong>Power analysis</strong> allows us to design experiments to do just that. Given:</p>
<ul>
<li>a desired power (0.8 or 80% is considered pretty good)</li>
<li>a significance level (0.05 or 5% is our trusty yet arbitrary steed once again)</li>
<li>an effect size that we would like to detect</li>
</ul>
<p>We can calculate the amount of data that we need to collect in our experiments. (Woohoo! it looks as if statistics will actually give us an answer at last rather than these perpetual shades-of-grey “maybes”).</p>
<p>The reality is that most of the easily usable power analysis functions all operate under the assumption that the data that you will collect will meet all of the assumptions of your chosen statistical test perfectly. So, for example, if you want to design an experiment investigating the effectiveness of a single drug compared to a placebo (so a simple t-test) and you want to know how many patients to have in each group in order for the test to work, then the standard power analysis techniques will still assume that all of the data that you end up collecting will meet the assumptions of the t-test that you have to carry out (sorry to have raised your hopes ever so slightly 😉).</p>
<div id="effect-size" class="section level3" number="28.2.1">
<h3>
<span class="header-section-number">28.2.1</span> Effect size<a class="anchor" aria-label="anchor" href="#effect-size"><i class="fas fa-link"></i></a>
</h3>
<p>As we shall see the commands for carrying out power analyses are very simple to implement apart from the concept of effect size. This is a tricky issue for most people to get to grips with for two reasons:</p>
<ol style="list-style-type: decimal">
<li>Effect size is related to biological significance rather than statistical significance</li>
<li>The way in which we specify effect sizes</li>
</ol>
<div class="highlight">
<p>With respect to the first point a common conversation goes a bit like this:</p>
<p>me: “So you’ve been told to carry out a power analysis, eh? Lucky you. What sort of effect size are you looking for?”</p>
<p>you: “I have no idea what you’re talking about. I want to know if my drug is any better than a placebo. How many patients do I need?”</p>
<p>me: “It depends on how big a difference you think your drug will have compared to the placebo.”</p>
<p>you: “I haven’t carried out my experiment yet, so I have absolutely no idea how big the effect will be!”</p>
<p>me: <sigh></sigh></p>
<p>(To be honest this would be a relatively well-informed conversation: <a href="https://www.youtube.com/watch?v=Hz1fyhVOjr4">this is much closer</a> to how things actually go)</p>
</div>
<p>The key point about effect sizes and power analyses is that you need to specify an effect size that you would be interested in observing, or one that would be biologically relevant to see. There may well actually be a 0.1% difference in effectiveness of your drug over a placebo but designing an experiment to detect that would require markedly more individuals than an experiment that was trying to detect a 50% difference in effectiveness. In reality there are three places we can get a sense of effect sizes from:</p>
<ol style="list-style-type: decimal">
<li>A pilot study</li>
<li>Previous literature or theory</li>
<li>Jacob Cohen</li>
</ol>
<p><a href="https://en.wikipedia.org/wiki/Jacob_Cohen_(statistician)">Jacob Cohen</a> was an American statistician who developed a large set of measures for effect sizes (which we will use today). He came up with a rough set of numerical measures for “small”, “medium” and “large” effect sizes that are still in use today. These do come with some caveats though; Jacob was a psychologist and so his assessment of what was a large effect may be somewhat different from yours. They do form a useful starting point however.</p>
<p>There a lot of different ways of specifying effects sizes, but we can split them up into three distinct families of estimates:</p>
<ol style="list-style-type: decimal">
<li>
<strong>Correlation estimates</strong>: these use R<sup>2</sup> as a measure of variance explained by a model (for linear models, anova etc. A large R<sup>2</sup> value would indicate that a lot of variance has been explained by our model and we would expect to see a lot of difference between groups, or a tight cluster of points around a line of best fit. The argument goes that we would need fewer data points to observe such a relationship with confidence. Trying to find a relationship with a low R<sup>2</sup> value would be trickier and would therefore require more data points for an equivalent power.</li>
<li>
<strong>Difference between means</strong>: these look at how far apart the means of two groups are, measured in units of standard deviations (for t-tests). An effect size of 2 in this case would be interpreted as the two groups having means that were two standard deviations away from each other (quite a big difference), whereas an effect size of 0.2 would be harder to detect and would require more data to pick it up.</li>
<li>
<strong>Difference between count data</strong>: these I freely admit I have no idea how to intuitively explain them (shock, horror). Mathematically they are based on the chi-squared statistic but that’s as good as I can tell you I’m afraid. They are, however, pretty easy to calculate.</li>
</ol>
<p>For reference here are some of Cohen’s suggested values for effect sizes for different tests. You’ll probably be surprised by how small some of these are.</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">Test</th>
<th align="left">Small</th>
<th align="left">Medium</th>
<th align="left">Large</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">t-tests</td>
<td align="left">0.2</td>
<td align="left">0.5</td>
<td align="left">0.8</td>
</tr>
<tr class="even">
<td align="left">anova</td>
<td align="left">0.1</td>
<td align="left">0.25</td>
<td align="left">0.4</td>
</tr>
<tr class="odd">
<td align="left">linear models</td>
<td align="left">0.02</td>
<td align="left">0.15</td>
<td align="left">0.35</td>
</tr>
<tr class="even">
<td align="left">chi-squared</td>
<td align="left">0.1</td>
<td align="left">0.3</td>
<td align="left">0.5</td>
</tr>
</tbody>
</table></div>
<p>We will look at how to carry out power analyses and estimate effect sizes in this section.</p>
</div>
</div>
<div id="packages" class="section level2" number="28.3">
<h2>
<span class="header-section-number">28.3</span> Packages<a class="anchor" aria-label="anchor" href="#packages"><i class="fas fa-link"></i></a>
</h2>
<p>We will be using the <code>pwr</code> package during this section, which contains functions that allow us to perform power calculations. Please install it now.</p>
<p>You can do this by running the following code in your console:</p>
<div class="sourceCode" id="cb314"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"pwr"</span><span class="op">)</span></code></pre></div>
<p>Next, load it by running:</p>
<div class="sourceCode" id="cb315"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/heliosdrm/pwr">pwr</a></span><span class="op">)</span></code></pre></div>
</div>
<div id="section-commands-14" class="section level2" number="28.4">
<h2>
<span class="header-section-number">28.4</span> Section commands<a class="anchor" aria-label="anchor" href="#section-commands-14"><i class="fas fa-link"></i></a>
</h2>
<p>New commands used in this section:</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="50%">
<col width="50%">
</colgroup>
<thead><tr class="header">
<th align="left">Function</th>
<th align="left">Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left"><code><a href="https://rdrr.io/pkg/pwr/man/pwr.t.test.html">pwr.t.test()</a></code></td>
<td align="left">Power analysis for 1-sample, 2-sample and paired t-tests</td>
</tr>
<tr class="even">
<td align="left"><code><a href="https://rdrr.io/pkg/pwr/man/pwr.f2.test.html">pwr.f2.test()</a></code></td>
<td align="left">Power analysis for linear models</td>
</tr>
<tr class="odd">
<td align="left"><code><a href="https://rdrr.io/pkg/pwr/man/cohen.ES.html">cohen.ES()</a></code></td>
<td align="left">Conventional effect sizes for all tests</td>
</tr>
<tr class="even">
<td align="left"><code><a href="https://rpkgs.datanovia.com/rstatix/reference/cohens_d.html">cohens_d()</a></code></td>
<td align="left">Compute the effect size for t-test</td>
</tr>
</tbody>
</table></div>
</div>
<div id="t-tests" class="section level2" number="28.5">
<h2>
<span class="header-section-number">28.5</span> t-tests<a class="anchor" aria-label="anchor" href="#t-tests"><i class="fas fa-link"></i></a>
</h2>
<p>Let’s assume that we want to design an experiment to determine whether there is a difference in the mean price of what male and female students pay at a cafe. How many male and female students would we need to observe in order to detect a “medium” effect size with 80% power and a significance level of 0.05?</p>
<p>We first need to think about which test we would use to analyse the data. Here we would have two groups of continuous response. Clearly a t-test.</p>
<div id="get-the-effect-size" class="section level3" number="28.5.1">
<h3>
<span class="header-section-number">28.5.1</span> Get the effect size<a class="anchor" aria-label="anchor" href="#get-the-effect-size"><i class="fas fa-link"></i></a>
</h3>
<p>Now we need to work out what a “medium” effect size would be. In the absence of any other information we appeal to Cohen’s conventional values:</p>
<div class="sourceCode" id="cb316"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/cohen.ES.html">cohen.ES</a></span><span class="op">(</span>test <span class="op">=</span> <span class="st">"t"</span>, size <span class="op">=</span> <span class="st">"medium"</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##      Conventional effect size from Cohen (1982) 
## 
##            test = t
##            size = medium
##     effect.size = 0.5</code></pre>
<p>This function just returns the default conventional values for effect sizes as determined by Jacob Cohen back in the day. It just saves us scrolling back up the page to look at the table I provided. It only takes two arguments:</p>
<ul>
<li>test which is one of
<ul>
<li>“t”, for t-tests,</li>
<li>“anova” for anova,</li>
<li>“f2” for linear models</li>
<li>“chisq” for chi-squared test</li>
</ul>
</li>
<li>size, which is just one of “small”, “medium” or “large”.</li>
</ul>
<p>The bit we want is on the bottom line; we apparently want an effect size of 0.5.
For this sort of study effect size is measured in terms of Cohen’s d statistic. This is simply a measure of how different the means of the two groups are expressed in terms of the number of standard deviations they are apart from each other. So, in this case we’re looking to detect two means that are 0.5 standard deviations away from each other. In a minute we’ll look at what this means for real data.</p>
</div>
<div id="carry-out-a-power-analysis" class="section level3" number="28.5.2">
<h3>
<span class="header-section-number">28.5.2</span> Carry out a power analysis<a class="anchor" aria-label="anchor" href="#carry-out-a-power-analysis"><i class="fas fa-link"></i></a>
</h3>
<p>We do this as follows:</p>
<div class="sourceCode" id="cb318"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.t.test.html">pwr.t.test</a></span><span class="op">(</span>d <span class="op">=</span> <span class="fl">0.5</span>, sig.level <span class="op">=</span> <span class="fl">0.05</span>, power <span class="op">=</span> <span class="fl">0.8</span>,
           type <span class="op">=</span> <span class="st">"two.sample"</span>, alternative <span class="op">=</span> <span class="st">"two.sided"</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 63.76561
##               d = 0.5
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<p>The first line is what we’re looking for <code>n = 63.76</code> tells that we need 64 (rounding up) students in each group (so 128 in total) in order to carry out this study with sufficient power. The other lines should be self-explanatory (well they should be by this stage; if you need me to tell you that the function is just returning the values that you’ve just typed in then you have bigger problems to worry about).</p>
<p>The <code><a href="https://rdrr.io/pkg/pwr/man/pwr.t.test.html">pwr.t.test()</a></code> function has six arguments. Two of them specify what sort of t-test you’ll be carrying out
* <code>type</code>; which describes the type of t-test you will eventually be carrying out (one of <code>two.sample</code>, <code>one.sample</code> or <code>paired</code>), and
* <code>alternative</code>; which describes the type of alternative hypothesis you want to test (one of <code>two.sided</code>, <code>less</code> or <code>greater</code>)</p>
<p>The other four arguments are what is used in the power analysis:</p>
<ul>
<li>
<code>d</code>; this is the effect size, a single number calculated using Cohen’s d statistic.</li>
<li>
<code>sig.level</code>; this is the significance level</li>
<li>
<code>power</code>; is the power</li>
<li>
<code>n</code>; this is the number of observations per sample.</li>
</ul>
<p>The function works by allowing you to specify any three of these four arguments and the function works out the fourth. In the example above we have used the test in the standard fashion by specifying power, significance and desired effect size and getting the function to tell us the necessary sample size.</p>
<p>We can use the function to answer a different question:</p>
<blockquote>
<p>If I know in advance that I can only observe 30 students per group, what is the effect size that I should be able to observe with 80% power at a 5% significance level?</p>
</blockquote>
<p>Let’s see how we do this:</p>
<div class="sourceCode" id="cb320"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.t.test.html">pwr.t.test</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">30</span>, sig.level <span class="op">=</span> <span class="fl">0.05</span>, power <span class="op">=</span> <span class="fl">0.8</span>,
           type <span class="op">=</span> <span class="st">"two.sample"</span>, alternative <span class="op">=</span> <span class="st">"two.sided"</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 30
##               d = 0.7356292
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<p>This time we want to see what the effect size is so we look at the second line and we can see that an experiment with this many people would only be expected to detect a difference in means of <code>d = 0.74</code> standard deviations. Is this good or bad? Well, it depends on the natural variation of your data; if your data is really noisy then it will have a large variation and a large standard deviation which will mean that 0.74 standard deviations might actually be quite a big difference between your groups. If on the other hand your data doesn’t vary very much, then 0.74 standard deviations might actually be a really small number and this test could pick up even quite small differences in mean.</p>
<p>In both of the previous two examples we were a little bit context-free in terms of effect size. Let’s look at how we can use a pilot study with real data to calculate effect sizes and perform a power analysis to inform a future study.</p>
<p>Let’s look again at the <code>fishlength</code> data we saw in the first practical relating to the lengths of fish from two separate rivers. This is saved as <code>data/tidy/CS6-fishlength.csv</code>.</p>
<div class="sourceCode" id="cb322"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># read in the data</span>
<span class="va">fishlength</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/tidy/CS6-fishlength.csv"</span><span class="op">)</span>

<span class="co"># look at the data</span>
<span class="va">fishlength</span></code></pre></div>
<pre><code>## # A tibble: 68 × 3
##       id river   length
##    &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;
##  1     1 Guanapo   19.1
##  2     2 Guanapo   23.3
##  3     3 Guanapo   18.2
##  4     4 Guanapo   16.4
##  5     5 Guanapo   19.7
##  6     6 Guanapo   16.6
##  7     7 Guanapo   17.5
##  8     8 Guanapo   19.9
##  9     9 Guanapo   19.1
## 10    10 Guanapo   18.8
## # … with 58 more rows</code></pre>
<div class="sourceCode" id="cb324"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># summarise the data</span>
<span class="va">fishlength</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">id</span><span class="op">)</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">river</span><span class="op">)</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rpkgs.datanovia.com/rstatix/reference/get_summary_stats.html">get_summary_stats</a></span><span class="op">(</span>type <span class="op">=</span> <span class="st">"common"</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 11
##   river   variable     n   min   max median   iqr  mean    sd    se    ci
##   &lt;chr&gt;   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Aripo   length      39  17.5  26.4   20.1   2.2  20.3  1.78 0.285 0.577
## 2 Guanapo length      29  11.2  23.3   18.8   2.2  18.3  2.58 0.48  0.983</code></pre>
<div class="sourceCode" id="cb326"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># visualise the data</span>
<span class="va">fishlength</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">river</span>, y <span class="op">=</span> <span class="va">length</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs6-practical-power_analysis_files/figure-html/unnamed-chunk-7-1.png" width="672"></div>
<div class="sourceCode" id="cb327"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># perform t-test</span>
<span class="va">fishlength</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rpkgs.datanovia.com/rstatix/reference/t_test.html">t_test</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">river</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 8
##   .y.    group1 group2     n1    n2 statistic    df       p
## * &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;   &lt;int&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
## 1 length Aripo  Guanapo    39    29      3.64  46.9 0.00067</code></pre>
<p>From the summary statistics we can see that there are 39 observations for the Aripo river and only 29 observations for the Guanapo river. From the box plot we see that the groups appear to have different means and from the t-test analysis we can see that this difference is significant.</p>
<p>Can we use this information to design a more efficient experiment? One that we would be confident was powerful enough to pick up a difference in means as big as was observed in this study but with fewer observations?</p>
<p>Let’s first work out exactly what the effect size of this previous study really was by estimating Cohen’s d using this data.</p>
<div class="sourceCode" id="cb329"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fishlength</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rpkgs.datanovia.com/rstatix/reference/cohens_d.html">cohens_d</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">river</span>, var.equal <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   .y.    group1 group2  effsize    n1    n2 magnitude
## * &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;     &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;ord&gt;    
## 1 length Aripo  Guanapo   0.942    39    29 large</code></pre>
<p>The <code><a href="https://rpkgs.datanovia.com/rstatix/reference/cohens_d.html">cohens_d()</a></code> function calculates the effect size using the formula of the test. The <code>effsize</code> column contains the information that we want, in this case 0.94 .</p>
<p>We can know actually answer our question and see how many fish we really need to catch in the future:</p>
<div class="sourceCode" id="cb331"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.t.test.html">pwr.t.test</a></span><span class="op">(</span>d <span class="op">=</span> <span class="fl">0.94</span>, power <span class="op">=</span> <span class="fl">0.8</span>, sig.level <span class="op">=</span> <span class="fl">0.05</span>,
           type <span class="op">=</span> <span class="st">"two.sample"</span>, alternative <span class="op">=</span> <span class="st">"two.sided"</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 18.77618
##               d = 0.94
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<p>From this we can see that any future experiments would really only need to use 19 fish for each group (18.77 from the first line rounded up, so no fish will be harmed during the experiment…) if we wanted to be confident of detecting the difference we observed in the previous study.</p>
<p>This approach can also be used when the pilot study showed a smaller effect size that wasn’t observed to be significant (indeed arguably, a pilot study shouldn’t really concern itself with significance but should only really be used as a way of assessing potential effect sizes which can then be used in a follow-up study).</p>
</div>
</div>
<div id="exercise-one-sample" class="section level2" number="28.6">
<h2>
<span class="header-section-number">28.6</span> Exercise: one-sample<a class="anchor" aria-label="anchor" href="#exercise-one-sample"><i class="fas fa-link"></i></a>
</h2>
<div class="exercise">
<p><span id="exr:unlabeled-div-21" class="exercise"><strong>Exercise 28.1  </strong></span>Performing a power analysis on a one-sample data set</p>
<p>Load in <code>data/tidy/CS6-onesample.csv</code> (this is the same data we looked at in the earlier practical containing information on fish lengths from the Guanapo river).</p>
<ol style="list-style-type: lower-alpha">
<li>Assume this was a pilot study and analyse the data using a one-sample t-test to see if there is any evidence that the mean length of fish differs from 19 cm.</li>
<li>Use the results of this analysis to estimate the effect size.</li>
<li>Work out how big a sample size would be required to detect an effect this big with power 0.8 and significance 0.05.</li>
<li>How would the sample size change if we wanted 0.9 power and significance 0.01?</li>
</ol>
<details><summary>
Answer
</summary><p>First, read in the data:</p>
<div class="sourceCode" id="cb333"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fish_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/tidy/CS6-onesample.csv"</span><span class="op">)</span></code></pre></div>
<p>Let’s run the one-sample t-test as we did before:</p>
<div class="sourceCode" id="cb334"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fish_data</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rpkgs.datanovia.com/rstatix/reference/t_test.html">t_test</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="fl">1</span>,
         mu <span class="op">=</span> <span class="fl">20</span>,
         alternative <span class="op">=</span> <span class="st">"two.sided"</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   .y.    group1 group2         n statistic    df       p
## * &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;      &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
## 1 length 1      null model    29     -3.55    28 0.00139</code></pre>
<p>There does appear to be a statistically significant result here; the mean length of the fish appears to be different from 20 cm.</p>
<p>Let’s calculate the effect size using these data. This gives us the following output for the effect size in terms of the Cohen’s d metric.</p>
<div class="sourceCode" id="cb336"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fish_data</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rpkgs.datanovia.com/rstatix/reference/cohens_d.html">cohens_d</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="fl">1</span>, mu <span class="op">=</span> <span class="fl">20</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 6
##   .y.    group1 group2     effsize     n magnitude
## * &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;        &lt;dbl&gt; &lt;int&gt; &lt;ord&gt;    
## 1 length 1      null model  -0.659    29 moderate</code></pre>
<p>Our effect size is -0.66 which is a moderate effect size. This is pretty good and it means we might have been able to detect this effect with fewer samples.</p>
<div class="Note">
<p>Although the effect size here is negative, it does not matter in terms of the power calculations whether it’s negative or positive.</p>
</div>
<p>So, let’s do the power analysis to actually calculate the minimum sample size required:</p>
<div class="sourceCode" id="cb338"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.t.test.html">pwr.t.test</a></span><span class="op">(</span>d <span class="op">=</span> <span class="op">-</span><span class="fl">0.6590669</span>, sig.level <span class="op">=</span> <span class="fl">0.05</span>, power <span class="op">=</span> <span class="fl">0.8</span>,
           type <span class="op">=</span> <span class="st">"one.sample"</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 20.07483
##               d = 0.6590669
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided</code></pre>
<p>We would need 21 (you round up the n value) observations in our experimental protocol in order to be able to detect an effect size this big (small?) at a 5% significance level and 80% power. Let’s see what would happen if we wanted to be even more stringent:</p>
<div class="sourceCode" id="cb340"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.t.test.html">pwr.t.test</a></span><span class="op">(</span>d <span class="op">=</span> <span class="op">-</span><span class="fl">0.6590669</span>, sig.level <span class="op">=</span> <span class="fl">0.01</span>, power <span class="op">=</span> <span class="fl">0.9</span>,
           type <span class="op">=</span> <span class="st">"one.sample"</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 37.62974
##               d = 0.6590669
##       sig.level = 0.01
##           power = 0.9
##     alternative = two.sided</code></pre>
<p>Then we’d need 38 observations! We would need to do a bit more work if we wanted to work to this level of significance and power. Are such small differences in fish length biologically meaningful?</p>
</details>
</div>
</div>
<div id="exercise-two-sample-paired" class="section level2" number="28.7">
<h2>
<span class="header-section-number">28.7</span> Exercise: two-sample paired<a class="anchor" aria-label="anchor" href="#exercise-two-sample-paired"><i class="fas fa-link"></i></a>
</h2>
<div class="exercise">
<p><span id="exr:unlabeled-div-22" class="exercise"><strong>Exercise 28.2  </strong></span>Power analysis on a paired two-sample data set</p>
<p>Load in <code>data/tidy/CS6-twopaired.csv</code> (again this is the same data that we used in an earlier practical and relates to cortisol levels measured on 20 participants in the morning and evening).</p>
<ol style="list-style-type: lower-alpha">
<li>first carry out a power analysis to work out how big of an effect size this experiment should be able to detect at a power of 0.8 and significance level of 0.05. Don’t look at the data just yet!</li>
<li>Now calculate the actual observed effect size from the study.</li>
<li>If you were to repeat the study in the future, how many observations would be necessary to detect the observed effect with 80% power and significance level 0.01?</li>
</ol>
<details><summary>
Answer
</summary><p>First, read in the data:</p>
<div class="sourceCode" id="cb342"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">cortisol</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/tidy/CS6-twopaired.csv"</span><span class="op">)</span></code></pre></div>
<p>We have a paired dataset with 20 pairs of observations, what sort of effect size could we detect at a significance level of 0.05 and power of 0.8?</p>
<div class="sourceCode" id="cb343"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.t.test.html">pwr.t.test</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">20</span>, sig.level <span class="op">=</span> <span class="fl">0.05</span>, power <span class="op">=</span> <span class="fl">0.8</span>,
           type <span class="op">=</span> <span class="st">"paired"</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##      Paired t test power calculation 
## 
##               n = 20
##               d = 0.6604413
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number of *pairs*</code></pre>
<p>Remember that we get effect size measured in Cohen’s d metric. So here this experimental design would be able to detect a d value of 0.66 (2dp) which is a medium to large effect size.</p>
<p>Now let’s look at the actual data and work out what the effect size actually is:</p>
<div class="sourceCode" id="cb345"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">cortisol</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rpkgs.datanovia.com/rstatix/reference/cohens_d.html">cohens_d</a></span><span class="op">(</span><span class="va">cortisol</span> <span class="op">~</span> <span class="va">time</span>, paired <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   .y.      group1  group2  effsize    n1    n2 magnitude
## * &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;ord&gt;    
## 1 cortisol evening morning   -1.16    20    20 large</code></pre>
<p>This value, -1.16, is a massive effect size. It’s quite likely that we actually have more participants in this study than we actually need given such a large effect. Let calculate how many individuals we would actually need:</p>
<div class="sourceCode" id="cb347"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.t.test.html">pwr.t.test</a></span><span class="op">(</span>d <span class="op">=</span> <span class="op">-</span><span class="fl">1.159019</span>, sig.level <span class="op">=</span> <span class="fl">0.01</span>, power <span class="op">=</span> <span class="fl">0.8</span>,
           type <span class="op">=</span> <span class="st">"paired"</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##      Paired t test power calculation 
## 
##               n = 12.10628
##               d = 1.159019
##       sig.level = 0.01
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number of *pairs*</code></pre>
<p>So we would have only needed 13 pairs of participants in this study given the size of effect we were trying to detect.</p>
</details>
</div>
</div>
<div id="linear-model-power-calculations" class="section level2" number="28.8">
<h2>
<span class="header-section-number">28.8</span> Linear model power calculations<a class="anchor" aria-label="anchor" href="#linear-model-power-calculations"><i class="fas fa-link"></i></a>
</h2>
<p>Thankfully the ideas we’re already covered in the t-test section should see us in good stead going forward and I can stop writing everything out in such excruciating detail (I do have other things to do you know).</p>
<p>For linear models we’ll just use <code><a href="https://rdrr.io/pkg/pwr/man/pwr.f2.test.html">pwr.f2.test()</a></code> to do the power calculation and we won’t need a function for effect sizes (because it’s just based on R<sup>2</sup> and we should just be able to read that off the screen).</p>
<p>Read in <code>data/tidy/CS6-lobsters.csv</code>. This dataset was used in an earlier practical and describes the effect on lobster weight of three different food sources.</p>
<p>Type this in:</p>
<div class="sourceCode" id="cb349"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># read in the data</span>
<span class="va">lobsters</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/tidy/CS6-lobsters.csv"</span><span class="op">)</span>

<span class="co"># visualise the data</span>
<span class="va">lobsters</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">diet</span>, y <span class="op">=</span> <span class="va">weight</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs6-practical-power_analysis_files/figure-html/unnamed-chunk-19-1.png" width="672"></div>
<div class="sourceCode" id="cb350"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># define the linear model</span>
<span class="va">lm_lobster</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">weight</span> <span class="op">~</span> <span class="va">diet</span>,
                 data <span class="op">=</span> <span class="va">lobsters</span><span class="op">)</span>

<span class="co"># perform ANOVA on model</span>
<span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">lm_lobster</span><span class="op">)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: weight
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## diet       2 1567.2  783.61  1.6432 0.2263
## Residuals 15 7153.1  476.87</code></pre>
<ul>
<li>the box plot shows us that there might well be some differences between groups</li>
<li>the ANOVA analysis though shows that there isn’t sufficient evidence to support that claim given the insignificant p-value we observe.</li>
</ul>
<p>So the question we can ask is:</p>
<blockquote>
<p>If there really is a difference between the different food sources as big as appears here, how big a sample would we need in order to be able to detect it statistically?</p>
</blockquote>
<p>First let’s calculate the observed effect size from this study. For linear models the effect size is called Cohen’s f<sup>2</sup>. We can calculate it easily by using the R<sup>2</sup> value from the model fit and shoving it in the following formula:</p>
<p><span class="math display">\[\begin{equation}
f^2 = \frac{R^2}{1-R^2}
\end{equation}\]</span></p>
<p>We find R<sup>2</sup> from the anova on <code>lm_lobster</code> and then we can calculate Cohen’s f^2:</p>
<div class="sourceCode" id="cb352"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># get the effect size for ANOVA</span>
<span class="va">R2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rpkgs.datanovia.com/rstatix/reference/eta_squared.html">eta_squared</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">lm_lobster</span><span class="op">)</span><span class="op">)</span>

<span class="va">R2</span></code></pre></div>
<pre><code>##      diet 
## 0.1797219</code></pre>
<div class="sourceCode" id="cb354"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># calculate Cohen's f2</span>
<span class="va">R2</span> <span class="op">/</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">R2</span><span class="op">)</span></code></pre></div>
<pre><code>##      diet 
## 0.2190987</code></pre>
<p>So now we’ve got Cohen’s f<sup>2</sup>. There’s one more thing that we need for the power calculation for a linear model (and this is where it gets a bit arbitrary); the degrees of freedom. We can either read those off the very bottom line of the <code>anova(lm_lobster)</code> output or we can extract them as follows:</p>
<div class="sourceCode" id="cb356"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># get degrees of freedom</span>
<span class="va">lm_lobster</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rpkgs.datanovia.com/rstatix/reference/anova_summary.html">anova_summary</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##   Effect DFn DFd     F     p p&lt;.05  ges
## 1   diet   2  15 1.643 0.226       0.18</code></pre>
<p>We have two different degrees of freedom: the <strong>numerator degrees of freedom</strong> (<code>DFn</code>) and the <strong>denominator degrees of freedom</strong> (<code>DFd</code>).Here the numerator degrees of freedom is 2. This is the number that we want. It is simply the number of parameters in the model minus 1. In this model there are three parameters for the three groups, so 3 - 1 = 2 (see the maths isn’t too bad). The other number is called the denominator degrees of freedom, which in this case is 15. This is actually the number we want the power analysis to calculate as it’s a proxy for the number of observations used in the model, and we’ll see how in a minute.</p>
<p>So, we now want to run a power analysis for this linear model, using the following information:</p>
<ul>
<li>power = 0.8</li>
<li>significance = 0.05</li>
<li>effect size = 0.219</li>
<li>numerator DF = 2</li>
</ul>
<p>We can feed this into the <code><a href="https://rdrr.io/pkg/pwr/man/pwr.f2.test.html">pwr.f2.test()</a></code> function, where we use</p>
<ul>
<li>
<code>u</code> to represent the numerator DF value</li>
<li>
<code>f2</code> to represent Cohen’s f<sup>2</sup> effect size value</li>
</ul>
<div class="sourceCode" id="cb358"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.f2.test.html">pwr.f2.test</a></span><span class="op">(</span>u <span class="op">=</span> <span class="fl">2</span>, f2 <span class="op">=</span> <span class="fl">0.219</span>,
            sig.level <span class="op">=</span> <span class="fl">0.05</span>, power <span class="op">=</span> <span class="fl">0.8</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##      Multiple regression power calculation 
## 
##               u = 2
##               v = 44.12292
##              f2 = 0.219
##       sig.level = 0.05
##           power = 0.8</code></pre>
<p>As before most of these numbers are just what you’ve put into the function yourself. The new number is <code>v</code>. This is the denominator degrees of freedom required for the analysis to have sufficient power. Thankfully this number is related to the number of observations that we should use in a straightforward manner:</p>
<p><span class="math inline">\(number\:of\:observations = u + v + 1\)</span></p>
<p>So in our case we would ideally have 48 observations (45 + 2 + 1, remembering to round up) in our experiment.
There are two questions you might now ask (if you’re still following all of this that is – you’re quite possibly definitely in need of a coffee by now):</p>
<ol style="list-style-type: decimal">
<li>how many observations should go into each group?
<ul>
<li>ideally they should be equally distributed (so in this case 16 per group).</li>
</ul>
</li>
<li>why is this so complicated, why isn’t there just a single function that just does this, and just tells me how many observations I need?
<ul>
<li>Very good question – I have no answer to that sorry – sometimes life is just hard.</li>
</ul>
</li>
</ol>
<p>The most challenging part for using power analyses for linear models is working out what the numerator degrees of freedom should be. The easiest way of thinking about it is to say that it’s the number of parameters in your model, excluding the intercept. If you look back at how we wrote out the linear model equations, then you should be able to see how many non-zero parameters would be expected. For some of the simple cases the table below will help you, but for complex linear models you will need to write out the linear model equation and count parameters (sorry!).</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="50%">
<col width="50%">
</colgroup>
<thead><tr class="header">
<th align="left">Test</th>
<th align="left">u</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">one-way ANOVA</td>
<td align="left">no. of groups - 1</td>
</tr>
<tr class="even">
<td align="left">simple linear regression</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">two-way ANOVA with interaction</td>
<td align="left">no. of groups (<code>v1</code>) x no. of groups (<code>v2</code>) - 1</td>
</tr>
<tr class="even">
<td align="left">two-way ANOVA without interaction</td>
<td align="left">no. of groups (<code>v1</code>) + no. of groups (<code>v2</code>) - 2</td>
</tr>
<tr class="odd">
<td align="left">ANCOVA with interaction</td>
<td align="left">2 x no. of groups – 1</td>
</tr>
<tr class="even">
<td align="left">ANCOVA without interaction</td>
<td align="left">no. of groups</td>
</tr>
</tbody>
</table></div>
</div>
<div id="exercise-mussel-muscles" class="section level2" number="28.9">
<h2>
<span class="header-section-number">28.9</span> Exercise: Mussel muscles<a class="anchor" aria-label="anchor" href="#exercise-mussel-muscles"><i class="fas fa-link"></i></a>
</h2>
<div class="exercise">
<p><span id="exr:unlabeled-div-23" class="exercise"><strong>Exercise 28.3  </strong></span>Calculating effect size</p>
<p>The file <code>data/raw/CS6-shelllength.csv</code> contains information from a pilot study looking at whether the standardised length of the anterior adductor muscle scar in the mussel <em>Mytilus trossulus</em> differs across five locations around the world (well it might be of interest to someone…).</p>
<p>Find the effect size from this study and perform a power calculation (at 0.8 and 0.05 significance level) to determine how many mussel muscles need to be recorded in order to be confident that an effect really exists.</p>
<details><summary>
Answer
</summary><p>Let’s load in the data:</p>
<div class="sourceCode" id="cb360"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">musseldat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/tidy/CS6-shelllength.csv"</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 39 Columns: 2
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: ","
## chr (1): location
## dbl (1): length
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>Let’s just have a quick look at the data to see what we’re dealing with:</p>
<div class="sourceCode" id="cb362"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">musseldat</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">location</span>,
             y <span class="op">=</span> <span class="va">length</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs6-practical-power_analysis_files/figure-html/unnamed-chunk-24-1.png" width="672"></div>
<p>So we are effectively looking at a one-way ANOVA with five groups. This will be useful to know later.</p>
<p>Now we fit a linear model:</p>
<div class="sourceCode" id="cb363"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># define the model</span>
<span class="va">lm_mussel</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">location</span>,
                data <span class="op">=</span> <span class="va">musseldat</span><span class="op">)</span>

<span class="co"># summarise the model</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">lm_mussel</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = length ~ location, data = musseldat)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.025400 -0.007956  0.000100  0.007000  0.031757 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         0.078012   0.004454  17.517  &lt; 2e-16 ***
## locationNewport    -0.003212   0.006298  -0.510  0.61331    
## locationPetersburg  0.025430   0.006519   3.901  0.00043 ***
## locationTillamook   0.002187   0.005975   0.366  0.71656    
## locationTvarminne   0.017688   0.006803   2.600  0.01370 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.0126 on 34 degrees of freedom
## Multiple R-squared:  0.4559, Adjusted R-squared:  0.3918 
## F-statistic: 7.121 on 4 and 34 DF,  p-value: 0.0002812</code></pre>
<p>From this we get that the <span class="math inline">\(R^2\)</span> value is 0.4559 and we can use this to calculate Cohen’s <span class="math inline">\(f^2\)</span> value using the formula in the notes:</p>
<div class="sourceCode" id="cb365"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">f2</span> <span class="op">&lt;-</span> <span class="fl">0.4559</span> <span class="op">/</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="fl">0.4559</span><span class="op">)</span>
<span class="va">f2</span></code></pre></div>
<pre><code>## [1] 0.8378974</code></pre>
<p>Now, our model has 5 parameters (because we have 5 groups) and so the numerator degrees of freedom will be 4 <span class="math inline">\((5 - 1 = 4)\)</span>. This means that we can now carry our our power analysis:</p>
<div class="sourceCode" id="cb367"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.f2.test.html">pwr.f2.test</a></span><span class="op">(</span>u <span class="op">=</span> <span class="fl">4</span>, f2 <span class="op">=</span> <span class="fl">0.8378974</span>,
            sig.level <span class="op">=</span> <span class="fl">0.05</span> , power <span class="op">=</span> <span class="fl">0.8</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##      Multiple regression power calculation 
## 
##               u = 4
##               v = 14.62182
##              f2 = 0.8378974
##       sig.level = 0.05
##           power = 0.8</code></pre>
<p>This tells us that the denominator degrees of freedom should be 15 (14.62 rounded up), and this means that we would only need 20 observations in total across all five groups to detect this effect size (Remember: number of observations = numerator d.f. + denominator d.f. + 1)</p>
</details>
</div>
</div>
<div id="exercise-epilepsy" class="section level2" number="28.10">
<h2>
<span class="header-section-number">28.10</span> Exercise: epilepsy<a class="anchor" aria-label="anchor" href="#exercise-epilepsy"><i class="fas fa-link"></i></a>
</h2>
<div class="exercise">
<p><span id="exr:unlabeled-div-24" class="exercise"><strong>Exercise 28.4  </strong></span>Power and effect</p>
<p>The file <code>/data/raw/CS6-epilepsy1.csv</code> contains information on the ages and rates of seizures of 236 patients undertaking a clinical trial.</p>
<ol style="list-style-type: lower-alpha">
<li>Analyse the data using a linear model and calculate the effect size.</li>
<li>If there would be a relationship that large between age and seizure rate how big a study would be needed to observe the effect with a 90% power.</li>
</ol>
<details><summary>
Answer
</summary><p>Let’s load in the data:</p>
<div class="sourceCode" id="cb369"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">epilepsydat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/tidy/CS6-epilepsy1.csv"</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 236 Columns: 2
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: ","
## dbl (2): age, seizure
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>Let’s just have a quick look at the data to see what we’re dealing with:</p>
<div class="sourceCode" id="cb371"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">epilepsydat</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">age</span>,
             y <span class="op">=</span> <span class="va">seizure</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs6-practical-power_analysis_files/figure-html/unnamed-chunk-29-1.png" width="672"></div>
<p>So we are effectively looking at a simple linear regression here.</p>
<p>Now we fit a linear model:</p>
<div class="sourceCode" id="cb372"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># define the model</span>
<span class="va">lm_epilepsy</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">seizure</span> <span class="op">~</span> <span class="va">age</span>,
                  data <span class="op">=</span> <span class="va">epilepsydat</span><span class="op">)</span>

<span class="co"># summarise the model</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">lm_epilepsy</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = seizure ~ age, data = epilepsydat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.77513 -0.19585 -0.04333  0.22288  1.24168 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.814935   0.124857   6.527 4.12e-10 ***
## age         -0.001990   0.004303  -0.463    0.644    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.413 on 234 degrees of freedom
## Multiple R-squared:  0.0009134,  Adjusted R-squared:  -0.003356 
## F-statistic: 0.2139 on 1 and 234 DF,  p-value: 0.6441</code></pre>
<p>From this we get that the <span class="math inline">\(R^2\)</span> value is 0.0009134 (which is tiny!) and we can use this to calculate Cohen’s <span class="math inline">\(f^2\)</span> value using the formula in the notes:</p>
<div class="sourceCode" id="cb374"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">f2</span> <span class="op">&lt;-</span> <span class="fl">0.0009134</span> <span class="op">/</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="fl">0.0009134</span><span class="op">)</span>
<span class="va">f2</span></code></pre></div>
<pre><code>## [1] 0.0009142351</code></pre>
<p>This effect size is absolutely tiny. If we really wanted to design an experiment to pick up an effect size this small then we would expect that we’ll need 1000s of participants.</p>
<p>Now, our model has 2 parameters (an intercept and a slope) and so the numerator degrees of freedom (<code>u</code>) will be 1 (2 - 1 = 1!). This means that we can now carry our our power analysis:</p>
<div class="sourceCode" id="cb376"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.f2.test.html">pwr.f2.test</a></span><span class="op">(</span>u <span class="op">=</span> <span class="fl">1</span>, f2 <span class="op">=</span> <span class="fl">0.0009142351</span>,
            sig.level <span class="op">=</span> <span class="fl">0.05</span> , power <span class="op">=</span> <span class="fl">0.9</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##      Multiple regression power calculation 
## 
##               u = 1
##               v = 11493.05
##              f2 = 0.0009142351
##       sig.level = 0.05
##           power = 0.9</code></pre>
<p>This tells us that the denominator degrees of freedom (<code>v</code>) should be 11494 (11493.05 rounded up), and this means that we would need 11496 participants to detect this effect size (Remember: number of observations = numerator d.f. (<code>u</code>) + denominator d.f. (<code>v</code>) + 1).</p>
</details>
</div>
</div>
<div id="exercise-drug-versus-placebo" class="section level2" number="28.11">
<h2>
<span class="header-section-number">28.11</span> Exercise: drug versus placebo<a class="anchor" aria-label="anchor" href="#exercise-drug-versus-placebo"><i class="fas fa-link"></i></a>
</h2>
<div class="exercise">
<p><span id="exr:unlabeled-div-25" class="exercise"><strong>Exercise 28.5  </strong></span>Study size</p>
<p>We wish to test the effectiveness of a new drug against a placebo. It is thought that the gender and the age of the patients may have an effect on their response.</p>
<ol style="list-style-type: lower-alpha">
<li>Write down a linear model equation that might describe the relationship between these variables including all possible two-way interactions.</li>
<li>How big a study would we need to detect a medium effect size (according to Cohen) at a power of 90%, with significance level 0.05?</li>
</ol>
<details><summary>
Answer
</summary><p>Here we have a system with a single response variable, and three categorical predictor variables. One of them is <code>gender</code>, with two possible levels (M, F). One of them is <code>treatment</code>, again with two possible levels (Drug, placebo) and one of them is continuous (<code>age</code>). A linear model with all possible two-way interactions would look something like this:</p>
<p><code>response ~ treatment + gender + age + treatment:gender + treatment:age + age:gender</code></p>
<p>In order to do a power calculation for this set up, we’ll need four things:</p>
<ol style="list-style-type: decimal">
<li>the <strong>effect size</strong>. Here we’re told it’s a medium effect size according to Cohen so we can use his default values.</li>
<li>The <strong>desired power</strong>. Here we’re told it’s 90%</li>
<li>The <strong>significance level</strong> to work to. Again we’re told this is going to be 0.05.</li>
<li>The <strong>numerator degrees of freedom</strong>. This is the tricky bit. We can do this by adding up the degrees of freedom for each term separately.</li>
</ol>
<p>The effect size is easy to get:</p>
<div class="sourceCode" id="cb378"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/cohen.ES.html">cohen.ES</a></span><span class="op">(</span>test <span class="op">=</span> <span class="st">"f2"</span>, size <span class="op">=</span> <span class="st">"medium"</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##      Conventional effect size from Cohen (1982) 
## 
##            test = f2
##            size = medium
##     effect.size = 0.15</code></pre>
<p>Alternatively, we could have looked this up online (which may give us different values, or values that are relevant to a specific discipline).</p>
<p>The numerator degrees of freedom is best calculated by working out the degrees of freedom of each of the six terms separately and then adding these up.</p>
<p>There are three simple ideas here that you need:</p>
<ol style="list-style-type: decimal">
<li>The degrees of freedom for a categorical variable is just the number of groups - 1</li>
<li>The degrees of freedom for a continuous variable is always 1</li>
<li>the degrees of freedom for any interaction is simple the product of the degrees of the main effects involved in the interaction.</li>
</ol>
<p>So this means:</p>
<ul>
<li>The <code>df</code> for <code>gender</code> is 1 (2 groups - 1)</li>
<li>The <code>df</code> for <code>treatment</code> is 1 (2 groups -1)</li>
<li>The <code>df</code> for <code>age</code> is 1 (continuous predictor)</li>
<li>The <code>df</code> for <code>gender:treatment</code> is 1 (1 x 1)</li>
<li>The <code>df</code> for <code>gender:age</code> is 1 (1 x 1)</li>
<li>The <code>df</code> for <code>age:treatment</code> is 1 (1 x 1)</li>
</ul>
<p>Rather boring that all of them were 1 to be honest. Anyway, given that the denominator degrees of freedom is just the sum of all of these, we can see that <span class="math inline">\(u = 6\)</span>.</p>
<p>We now have all of the information to carry out the power analysis:</p>
<div class="sourceCode" id="cb380"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.f2.test.html">pwr.f2.test</a></span><span class="op">(</span>u <span class="op">=</span> <span class="fl">6</span>, f2 <span class="op">=</span> <span class="fl">0.15</span>,
            sig.level <span class="op">=</span> <span class="fl">0.05</span>, power <span class="op">=</span> <span class="fl">0.9</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##      Multiple regression power calculation 
## 
##               u = 6
##               v = 115.5826
##              f2 = 0.15
##       sig.level = 0.05
##           power = 0.9</code></pre>
<p>We get a denominator df of 116, which means that we would need at least 123 participants in our study (Remember: number of observations = numerator d.f. (u) + denominator d.f. (v) + 1). Given that we have four unique combinations of <code>gender</code> and <code>treatment</code>, it would be practically sensible to round this up to 124 participants so that we could have an equal number (31) in each combination of gender and treatment. It would also be sensible to aim for a similar distribution of age ranges in each group as well.</p>
</details>
</div>
</div>
<div id="key-points-10" class="section level2" number="28.12">
<h2>
<span class="header-section-number">28.12</span> Key points<a class="anchor" aria-label="anchor" href="#key-points-10"><i class="fas fa-link"></i></a>
</h2>
<div class="keypoints">
<ul>
<li>Power is the capacity of a test to detect significant results and is affected by
<ol style="list-style-type: decimal">
<li>the effect size</li>
<li>sample size</li>
<li>the significance level</li>
</ol>
</li>
<li>Power analysis optimises the trade-off between power, significance level and the desired effect size that we would like to detect</li>
<li>Point 3</li>
</ul>
</div>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="introduction-5.html"><span class="header-section-number">27</span> Introduction</a></div>
<div class="next"><a href="statistical-reporting.html"><span class="header-section-number">29</span> Statistical reporting</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#power-analysis"><span class="header-section-number">28</span> Power analysis</a></li>
<li><a class="nav-link" href="#objectives-14"><span class="header-section-number">28.1</span> Objectives</a></li>
<li>
<a class="nav-link" href="#background-6"><span class="header-section-number">28.2</span> Background</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#effect-size"><span class="header-section-number">28.2.1</span> Effect size</a></li></ul>
</li>
<li><a class="nav-link" href="#packages"><span class="header-section-number">28.3</span> Packages</a></li>
<li><a class="nav-link" href="#section-commands-14"><span class="header-section-number">28.4</span> Section commands</a></li>
<li>
<a class="nav-link" href="#t-tests"><span class="header-section-number">28.5</span> t-tests</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#get-the-effect-size"><span class="header-section-number">28.5.1</span> Get the effect size</a></li>
<li><a class="nav-link" href="#carry-out-a-power-analysis"><span class="header-section-number">28.5.2</span> Carry out a power analysis</a></li>
</ul>
</li>
<li><a class="nav-link" href="#exercise-one-sample"><span class="header-section-number">28.6</span> Exercise: one-sample</a></li>
<li><a class="nav-link" href="#exercise-two-sample-paired"><span class="header-section-number">28.7</span> Exercise: two-sample paired</a></li>
<li><a class="nav-link" href="#linear-model-power-calculations"><span class="header-section-number">28.8</span> Linear model power calculations</a></li>
<li><a class="nav-link" href="#exercise-mussel-muscles"><span class="header-section-number">28.9</span> Exercise: Mussel muscles</a></li>
<li><a class="nav-link" href="#exercise-epilepsy"><span class="header-section-number">28.10</span> Exercise: epilepsy</a></li>
<li><a class="nav-link" href="#exercise-drug-versus-placebo"><span class="header-section-number">28.11</span> Exercise: drug versus placebo</a></li>
<li><a class="nav-link" href="#key-points-10"><span class="header-section-number">28.12</span> Key points</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

					</div>
				</div>
				<!-- Related links -->
				<!--<div class="campl-column3 campl-secondary-content">
					<div class="campl-content-container">
						<div class="campl-heading-container">
							<h2>Related Links</h2>
						</div>
						<ul class='campl-unstyled-list campl-related-links'>
							<li><a href="#">Lorem ipsum dolor sit amet</a></li>
							<li><a href="#">Consectetur adipisicing elit</a></li>
							<li><a href="#">Sed do eiusmod tempor incididunt extra long wrapping on to two line</a></li>
							<li><a href="#">Labore et dolore magna aliqua</a></li>
							<li><a href="#">Ut enim ad minim veniam</a></li>
							<li><a href="#">Quis nostrud exercitation ullamco</a></li>
						</ul>
					</div>
					<div class="campl-content-container">
						<div class="campl-vertical-teaser campl-teaser campl-promo-teaser">
							<div class="campl-content-container campl-vertical-teaser-txt">
								<p class='campl-teaser-title'><a href="#">Promo teaser with title above</a></p>
							</div>
							<div class="campl-content-container campl-vertical-teaser-img">
								<a href="#" class="campl-teaser-img-link"><img alt=""  src="images/content/homepage-promo-placeholder.png" class="campl-scale-with-grid" /></a>
							</div>
							<div class="campl-content-container campl-vertical-teaser-txt clearfix">
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
								<a href="#4" class="campl-secondary-cta campl-float-right">Read more</a>
							</div>
						</div>
					</div>
				</div>-->
			</div>
		</div>
		<div class="campl-row campl-local-footer">
			<div class="campl-wrap clearfix">
				<div class="campl-column3 campl-footer-navigation">
					<div class="campl-content-container campl-navigation-list">
						<h3>Contact us</h3>
						 <div class="content">
						   <p>Bioinformatics Training Department of Genetics University of Cambridge Downing Street Cambridge CB2 3EH United Kingdom</p>
						   <h3>Contact:</h3> <a href="mailto:%20bioinfotraining@bio.cam.ac.uk">bioinfotraining@bio.cam.ac.uk</a>
						 </div>
					</div>
				</div>
				<div class="campl-column3 campl-footer-navigation">
					<div class="campl-content-container campl-navigation-list">
						<h3>Bioinformatics Training</h3>
						<ul class="campl-unstyled-list">
<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/undergraduate">Undergraduate training</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate">Postgraduate training</a>
							</li>
						</ul>
</div>
				</div>
				<div class="campl-column3 campl-footer-navigation">
					<div class="campl-content-container campl-navigation-list">
						<h3>Postgraduate Courses by Theme</h3>
						<ul class="campl-unstyled-list">
<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate/programming">Basic Skills and Programming</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate/services">Databases and Services</a>
							</li>
							<li>
							  <a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate/specialized">Specialised Topics</a>
							</li>
						</ul>
</div>
				</div>
				<div class="campl-column3 campl-footer-navigation last">
					<div class="campl-content-container campl-navigation-list">
						<h3>About Bioinformatics Training</h3>
						<ul class="campl-unstyled-list">
<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/about">About the Facility</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/about/findus">How to find us</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/about/visitors">Visiting Cambridge</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/privacy-and-cookie-policies">Privacy and Cookies policy</a>
							</li>
						</ul>
</div>
				</div>
			</div>
		</div>
	<div class="campl-row campl-global-footer">
		<div class="campl-wrap clearfix">
			<div class="campl-column3 campl-footer-navigation">
				<div class="campl-content-container campl-footer-logo">
					<img alt="University of Cambridge" src="images/interface/main-logo-small.png" height="38px;" class="campl-scale-with-grid"><p>© 2021 University of Cambridge</p>
						<ul class="campl-unstyled-list campl-global-footer-links">
<li>
								<a href="http://www.cam.ac.uk/university-a-z">University A-Z</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/contact-the-university">Contact the University</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-this-site/accessibility">Accessibility</a>
							</li>
							<li>
								<a href="http://www.admin.cam.ac.uk/univ/information/foi/">Freedom of information</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-this-site/terms-and-conditions">Terms and conditions</a>
							</li>
						</ul>
</div>
			</div>
			<div class="campl-column3 campl-footer-navigation">
				<div class="campl-content-container campl-navigation-list">

					<div class="link-list">
						<h3><a href="http://www.cam.ac.uk/study-at-cambridge">Study at Cambridge</a></h3>
						<ul class="campl-unstyled-list">
<li>
								<a href="http://www.study.cam.ac.uk/undergraduate/">Undergraduate</a>
							</li>
							<li>
								<a href="http://www.graduate.study.cam.ac.uk/">Graduate</a>
							</li>
							<li>
								<a href="http://www.internationalstudents.cam.ac.uk">International students</a>
							</li>
							<li>
								<a href="http://www.ice.cam.ac.uk">Continuing education</a>
							</li>
							<li>
								<a href="http://www.epe.admin.cam.ac.uk/">Executive and professional education</a>
							</li>
							<li>
								<a href="http://www.educ.cam.ac.uk">Courses in education</a>
							</li>
						</ul>
</div>
				</div>
			</div>
			<div class="campl-column3 campl-footer-navigation">
				<div class="campl-content-container campl-navigation-list">
					<h3><a href="http://www.cam.ac.uk/about-the-university">About the University</a></h3>
					<ul class="campl-unstyled-list campl-page-children">
<li>
							<a href="http://www.cam.ac.uk/about-the-university/how-the-university-and-colleges-work">How the University and Colleges work</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/about-the-university/visiting-the-university">Visiting the University</a>
						</li>
						<li>
							<a href="http://map.cam.ac.uk">Map</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/news">News</a>
						</li>
						<li>
							<a href="http://www.admin.cam.ac.uk/whatson/">Events</a>
						</li>
						<li>
							<a href="http://www.jobs.cam.ac.uk">Jobs</a>
						</li>
						<li>
							<a href="https://www.philanthropy.cam.ac.uk/">Give to Cambridge</a>
						</li>
					</ul>
</div>
			</div>
			<div class="campl-column3 campl-footer-navigation last">
				<div class="campl-content-container campl-navigation-list">
					<h3><a href="http://www.cam.ac.uk/research">Research at Cambridge</a></h3>
					<ul class="campl-unstyled-list">
<li>
							<a href="http://www.cam.ac.uk/research/news">News</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/research/features">Features</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/research/discussion">Discussion</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/research/spotlight-on">Spotlight on...</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/research/research-at-cambridge">About research at Cambridge</a>
						</li>
					</ul>
</div>
			</div>
		</div>
	</div>
	<!-- .campl-global-footer ends -->

<!--[if lte IE 8]>
</div>
<![endif]-->

	<script type="text/javascript" src="javascripts/libs/ios-orientationchange-fix.js"></script><script type="text/javascript" src="javascripts/libs/jquery-min.js"></script><script type="text/javascript" src="javascripts/libs/modernizr.js"></script><script type="text/javascript" src="javascripts/custom.js"></script><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
